name: Convert MD to JSON

on:
  push:
    branches:
      - main
      - 'claude/**'
    paths:
      - 'navigation-data.md'
  workflow_dispatch:  # 允许手动触发

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Convert Markdown to JSON
        run: |
          echo "🔄 开始转换 Markdown 到 JSON..."
          node convert.js

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet navigation-data.json; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "✅ JSON 文件无变化"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "📝 JSON 文件已更新"
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add navigation-data.json
          git commit -m "🤖 Auto-generated JSON from Markdown [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          echo "### 转换完成 ✨" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Markdown 文件: \`navigation-data.md\`" >> $GITHUB_STEP_SUMMARY
          echo "- JSON 文件: \`navigation-data.json\`" >> $GITHUB_STEP_SUMMARY
          echo "- 状态: ${{ steps.check_changes.outputs.changed == 'true' && '已更新并提交' || '无变化' }}" >> $GITHUB_STEP_SUMMARY
